feat: added Address validations
keep-starknet-strange/rosettanet pull request #44
Opened 2024-02-24 19:35 UTC by ktarun1419

2024-02-25 08:42 UTC, ermvrs approved these changes

2024-02-25 08:42 UTC, ermvrs commented on src/utils/validations.ts
>  /* eslint-disable @typescript-eslint/no-unused-vars */
Can you remove eslint disable line?

2024-02-25 08:42 UTC, ermvrs requested changes
Can you remove eslint disable

2024-02-25 09:20 UTC, ktarun1419 commented on src/utils/validations.ts
>  /* eslint-disable @typescript-eslint/no-unused-vars */
yes sure

2024-02-25 10:29 UTC, ermvrs approved these changes

2024-02-25 10:29 UTC, merged

2024-02-26 10:37 UTC, LucasLvy commented
@all-contributors please add @ktarun1419 code, test