Implement eth_getBlockTransactionCountByHash
keep-starknet-strange/rosettanet pull request #77
Opened 2024-03-04 18:42 UTC by princeibs

Implementation for https://github.com/keep-starknet-strange/rosettanet/issues/65

2024-03-04 19:00 UTC, AryanGodara requested changes
There might be just a small issue with Eth expecting a hex output, and starknet returning a decimal

2024-03-04 19:39 UTC, princeibs commented on src/rpc/calls/getBlockTransactionCountByHash.ts
> +    result: response.result,
Resolved

2024-03-04 19:39 UTC, princeibs commented on tests/rpc/calls/getBlockTransactionCountByHash.test.ts
> +    expect(response.result).toBe(41) // Verify here: https://testnet.starkscan.co/block/0x0627dadf33aecc02abe2530f1f2b091a24e7a119cc03851be4d559af47f22e93#transactions
Resolved

2024-03-05 12:54 UTC, ermvrs approved these changes

2024-03-05 12:55 UTC, merged