Add RPC function and test
keep-starknet-strange/rosettanet pull request #81
Opened 2024-03-06 11:28 UTC by muheebyusufbaba1

2024-03-15 21:06 UTC, AryanGodara requested changes
Just some small changes here and there

2024-03-15 21:06 UTC, AryanGodara commented on src/rpc/calls/getTransactionByBlockNumberAndIndex.ts
> +  // TODO: Validate block number
Use this method
```
export function validateBlockNumber(value: any): boolean {
  if (typeof value === 'number') {
    return !isNaN(value) && value >= 0;
  }

  return false;
}
```

See #79 to see how it's implemented there :)

2024-03-15 21:06 UTC, AryanGodara commented on tests/rpc/calls/getTransactionByBlockNumberAndIndex.test.ts
> +  it('Returns RPC error ', async () => {
The naming can be better. Currently it's difficult to guess "why" RPC error is returned
maybe try `invalid index param`?

2024-03-15 21:06 UTC, AryanGodara commented on tests/rpc/calls/getTransactionByBlockNumberAndIndex.test.ts
> +})
Add testcase for index out of bounds.

2024-03-15 21:08 UTC, AryanGodara commented
> #69

Write `closes #69` so github can detect you're working on that issue ;)

2024-03-16 16:17 UTC, muheebyusufbaba1 commented
All comments raised have been fixed @AryanGodara

2024-03-17 09:30 UTC, AryanGodara commented
> All comments raised have been fixed @AryanGodara

Awesome!

Also,
```txt
PARAMETERS:
QUANTITY|TAG - a block number, or the string "earliest", "latest" or "pending"
QUANTITY - the transaction index position.
```

Does the current implementation support me passing `earliest`, `latest`, and `pending`?

I think the validateBlockNumber function needs to be updated, and tests need to be added for these cases once you add this functionality

2024-04-13 09:40 UTC, ermvrs commented
please resolve conflicts

2024-04-14 05:46 UTC, merged